### ISSUE TITLE
rewrite in typescript

### ISSUE THREAD

**Issue by nhynes** [oasisprotocol/deoxysii-js#12]

**Comment by CedarMist** [comment]
You will be pleased to know my PR has re-written this library typescript, updated all the tooling, and reduces the bundled size for both CommonJS and ESM (with or without tree shaking).

minified + gzip it's about 3.5kb with no other dependencies, and it has a nice README too.

**Comment by nhynes** [comment]
I am pleased, thank you! I will probably update the vendored dependency at some point. I'm using aes-gcm-siv these days since it's portable and deoxysii hasn't really seemed to catch on, but I am very glad to be able to close this almost five year old issue 😄

**Comment by CedarMist** [comment]
Unfortunately AES-GCM-SIV isn't supported by the WebCrypto Subtle API :(

So regardless of if we use Deoxys-II or AES-GCM-SIV as the MR-AEAD algo it's going to end up as being a custom implementation.

Have added ticket #39 for porting to WebAssembly, I'm sure in another 5 years somebody will get round to doing that lol.

**Comment by nhynes** [comment]
> Unfortunately AES-GCM-SIV isn't supported by the WebCrypto Subtle API

It's not, but it is part of the `@noble/ciphers` suite, which is pretty good and well maintained!

**Comment by CedarMist** [comment]
It seems the `@noble/ciphers` implementation of AES-GCM-SIV is pure JS, whereas the `micro-aes-gcm` version uses `webcrypto.subtle` behind the scenes where possible (aside from the tag computation).

What about [AEAD_XCHACHA20_SIV_HMAC_SHA256](https://datatracker.ietf.org/doc/html/draft-madden-generalised-siv-00#section-3) ?
