### ISSUE TITLE
nit: arg order, naming

### ISSUE THREAD

**Issue by bennetyee** [oasisprotocol/deoxysii-js#7]
https://github.com/oasislabs/deoxysii.js/blob/6c2872b41c6811f0a49e897e19200b90ba2f110a/deoxysii.js#L568

feel free to ignore/close.  this is just a nit.  deoxysII doc https://competitions.cr.yp.to/round3/deoxysv141.pdf Alg 4 has argument order `N, A, C, tag`, but we have `nonce, ciphertext, associated-data` (`N, C, A`), because we have added the tag to the end of the ciphertext output in encrypt.  this matches the golang code, except there `dst` is a sliceForAppend and so an additional arg, and the functions are named `Seal` and `Open`.

encrypt in the pdf (Alg 3) is `N, A, M`, but in js it is `nonce, plaintext, assocatedData` (`N, M, A`).  which is consistent with the golang implementation.

do we want to have naming consistency w/ the golang code?  do we want to have argument order consistency with the defining document (vs golang)?  the code is not hard to read, but could lead to careless errors.  we have argument order consistency w/ golang right now but naming is not.  the pdf is  latex amsmath, so... whatever.  is there a js AEAD interface that really want `encrypt` and `decrypt` names?

**Comment by CedarMist** [comment]
Closing this as it's been a few years and it would be a pain to change the argument order for no significant gain.
